/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{source}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset */
        get: operations["dataset_api_datasets__source___dataset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{source}/{dataset}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Config */
        get: operations["dataset_config_api_datasets__source___dataset__config_get"];
        /** Save Dataset Config */
        put: operations["save_dataset_config_api_datasets__source___dataset__config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{source}/{dataset}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_datasets__source___dataset__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{source}/{dataset}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality */
        get: operations["quality_api_datasets__source___dataset__quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{source}/{dataset}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rows */
        get: operations["rows_api_datasets__source___dataset__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline-runs/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline Run
         * @description A pipeline run's record: its steps, constraints, profiles and lineage so far.
         */
        get: operations["pipeline_run_api_pipeline_runs__execution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipelines/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Pipeline Run
         * @description Start a run of pipelines/<name>.yaml. It is recorded as running before this answers,
         *     so its id can be followed at once; a dataset another run holds is refused (409).
         */
        post: operations["start_pipeline_run_api_pipelines__name__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_sources__source__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckResult */
        CheckResult: {
            /** Check Type */
            check_type: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Columns */
            columns: string[];
            /** Failing Rows */
            failing_rows: number | null;
            /** Message */
            message: string;
            /** Passed */
            passed: boolean;
            /** Position */
            position: number;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /**
             * Severity
             * @enum {string}
             */
            severity: "warn" | "error";
            /** Table Rows */
            table_rows: number | null;
        };
        /** Column */
        Column: {
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** ColumnProfile */
        ColumnProfile: {
            /** All Values */
            all_values?: components["schemas"]["ValueCount"][] | null;
            /** Appear Once */
            appear_once?: number | null;
            /** Distinct */
            distinct?: number | null;
            /** Histogram */
            histogram?: number[] | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "number" | "date" | "text" | "other";
            /** Least Used */
            least_used?: components["schemas"]["ValueCount"][] | null;
            /** Max */
            max?: string | number | boolean | null;
            /** Mean */
            mean?: string | number | boolean | null;
            /** Min */
            min?: string | number | boolean | null;
            /** Missing */
            missing: number;
            /** Most Used */
            most_used?: components["schemas"]["ValueCount"][] | null;
            /** Name */
            name: string;
            /** Pattern */
            pattern?: string | null;
            /** Pattern Share */
            pattern_share?: number | null;
            /** Type */
            type: string;
        };
        /**
         * ConfigEdit
         * @description One save of a dataset's settings: what it changed, and when.
         */
        ConfigEdit: {
            /** Changed */
            changed: {
                [key: string]: unknown;
            };
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
        };
        /** ConfigUpdate */
        ConfigUpdate: {
            /**
             * Accept Rebuild
             * @default false
             */
            accept_rebuild: boolean;
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /**
         * DatasetConfig
         * @description A dataset's settings as the file has them and as they are actually used.
         *
         *     `file` and `effective` hold the same fields, `editable`, in the order they are shown;
         *     `overridden` names the fields where the two differ, which are the ones stored as an edit.
         *     `columns` is the table's columns as stored, so the page can offer the names that exist.
         *
         *     A dataset's checks are edited as the YAML the file itself holds, so they also come back as
         *     text: `checks_yaml` is what is in force and `file_checks_yaml` is what the file says.
         */
        DatasetConfig: {
            /** Checks Yaml */
            checks_yaml: string;
            /** Columns */
            columns: components["schemas"]["Column"][];
            /** Connector Type */
            connector_type: string;
            /** Dataset */
            dataset: string;
            /** Editable */
            editable: string[];
            /** Effective */
            effective: {
                [key: string]: unknown;
            };
            /** File */
            file: {
                [key: string]: unknown;
            };
            /** File Checks Yaml */
            file_checks_yaml: string;
            /** History */
            history: components["schemas"]["ConfigEdit"][];
            /** Overridden */
            overridden: string[];
            /** Source */
            source: string;
        };
        /** DatasetDetail */
        DatasetDetail: {
            /** Columns */
            columns: components["schemas"]["Column"][];
            /** Connector Type */
            connector_type: string;
            /** Dataset */
            dataset: string;
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            last_run: components["schemas"]["RunSummary"] | null;
            /** Load Mode */
            load_mode: string;
            /** Primary Key */
            primary_key: string[];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Schedule */
            schedule: string | null;
            /** Source */
            source: string;
            state: components["schemas"]["SavedState"] | null;
            /** Table Name */
            table_name: string;
            /** Table Rows */
            table_rows: number | null;
            /** Versions */
            versions: components["schemas"]["SchemaVersion"][];
            /** Watermark */
            watermark: string | null;
        };
        /** DatasetItem */
        DatasetItem: {
            /** Connector Type */
            connector_type: string;
            /** Dataset */
            dataset: string;
            last_run: components["schemas"]["RunSummary"] | null;
            /** Load Mode */
            load_mode: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Schedule */
            schedule: string | null;
            /** Source */
            source: string;
            /** Table Name */
            table_name: string;
            /** Table Rows */
            table_rows: number | null;
        };
        /** DatasetProfile */
        DatasetProfile: {
            /** Columns */
            columns: components["schemas"]["ColumnProfile"][];
            /** Profiled Rows */
            profiled_rows: number;
            /** Sampled */
            sampled: boolean;
            /** Table Rows */
            table_rows: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
        };
        /**
         * LineageRecord
         * @description One place the data passed through, in order; a step with the settings it ran with. The
         *     run that took the data there is the ingest run for the source and RAW, the pipeline run
         *     for its steps and CLEAN: exactly one of the two ids.
         */
        LineageRecord: {
            /** Configuration */
            configuration?: {
                [key: string]: unknown;
            } | null;
            /** Execution Id */
            execution_id?: string | null;
            /** Ingest Run Id */
            ingest_run_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "source" | "raw" | "step" | "clean";
            /** Name */
            name: string;
            /** Step Position */
            step_position?: number | null;
        };
        /**
         * PipelineRun
         * @description One run of one pipeline version: what ran, over what, how it ended, and what it measured.
         *
         *     `failed_step` is the step it failed at; a run that failed elsewhere — its input, validation
         *     or publishing — has none, and `error` says where. `input_run_id` is the ingest run whose RAW
         *     it read; none when it failed before it found one.
         */
        PipelineRun: {
            /** Dataset */
            dataset: string;
            /** Ended At */
            ended_at: string | null;
            /** Error */
            error: string | null;
            /** Error Class */
            error_class: string | null;
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Failed Step */
            failed_step: number | null;
            /** Input Run Id */
            input_run_id: string | null;
            /** Lineage */
            lineage: components["schemas"]["LineageRecord"][];
            /** Pipeline */
            pipeline: string;
            /** Pipeline Id */
            pipeline_id: number;
            /** Profiles */
            profiles: components["schemas"]["ProfileRecord"][];
            /** Rows In */
            rows_in: number | null;
            /** Rows Out */
            rows_out: number | null;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed";
            /** Steps */
            steps: components["schemas"]["StepRecord"][];
            /** Trigger */
            trigger: string;
            /** Validation */
            validation: components["schemas"]["ValidationRecord"][];
            /** Version */
            version: number;
        };
        /**
         * PipelineRunAccepted
         * @description A pipeline run recorded as running; `GET /api/pipeline-runs/{execution_id}` follows it.
         */
        PipelineRunAccepted: {
            /** Dataset */
            dataset: string;
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Pipeline */
            pipeline: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Source */
            source: string;
            /** Version */
            version: number;
        };
        /**
         * ProfileRecord
         * @description One profile the run took: where, and its totals. The whole profile is stored by id.
         */
        ProfileRecord: {
            /** After Step */
            after_step: number | null;
            /** Duplicates */
            duplicates: number;
            /** Invalid Values */
            invalid_values: number;
            /** Missing Values */
            missing_values: number;
            /** Outliers */
            outliers: number;
            /** Profile Id */
            profile_id: number;
            /**
             * Profiled At
             * Format: date-time
             */
            profiled_at: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "raw" | "staging" | "clean";
            /** Table Rows */
            table_rows: number;
        };
        /** QualityReport */
        QualityReport: {
            /** Results */
            results: components["schemas"]["CheckResult"][];
            /** Run Id */
            run_id: string | null;
        };
        /** RowsPage */
        RowsPage: {
            /** Columns */
            columns: components["schemas"]["Column"][];
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: {
                [key: string]: string | number | boolean | {
                    [key: string]: unknown;
                } | unknown[] | null;
            }[];
        };
        /** RunAccepted */
        RunAccepted: {
            /** Datasets */
            datasets: string[];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Source */
            source: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Dataset */
            dataset: string;
            /** Ended At */
            ended_at: string | null;
            /** Error Class */
            error_class: string | null;
            /** Error Message */
            error_message: string | null;
            /** Error Traceback */
            error_traceback: string | null;
            /** Quality */
            quality: components["schemas"]["CheckResult"][];
            /** Rows Extracted */
            rows_extracted: number | null;
            /** Rows Loaded */
            rows_loaded: number | null;
            /** Rows Quarantined */
            rows_quarantined: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "skipped";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "scheduled";
        };
        /** RunItem */
        RunItem: {
            /** Dataset */
            dataset: string;
            /** Ended At */
            ended_at: string | null;
            /** Error Class */
            error_class: string | null;
            /** Error Message */
            error_message: string | null;
            /** Rows Extracted */
            rows_extracted: number | null;
            /** Rows Loaded */
            rows_loaded: number | null;
            /** Rows Quarantined */
            rows_quarantined: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "skipped";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "scheduled";
        };
        /** RunRequest */
        RunRequest: {
            /** Dataset */
            dataset?: string | null;
            /**
             * Full Refresh
             * @default false
             */
            full_refresh: boolean;
            /** Source */
            source: string;
        };
        /** RunSummary */
        RunSummary: {
            /** Ended At */
            ended_at: string | null;
            /** Rows Loaded */
            rows_loaded?: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "skipped";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "scheduled";
        };
        /** RunsPage */
        RunsPage: {
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Runs */
            runs: components["schemas"]["RunItem"][];
        };
        /** SavedState */
        SavedState: {
            /** File Path */
            file_path: string | null;
            /** File Sha256 */
            file_sha256: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            /** Watermark */
            watermark: string | null;
            /** Watermark Column */
            watermark_column: string | null;
            /** Watermark Type */
            watermark_type: string | null;
        };
        /** SchemaVersion */
        SchemaVersion: {
            /** Columns */
            columns: components["schemas"]["Column"][];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Version */
            version: number;
        };
        /** SourceDetail */
        SourceDetail: {
            /** Connection */
            connection: {
                [key: string]: unknown;
            };
            /** Connector Type */
            connector_type: string;
            /** Datasets */
            datasets: components["schemas"]["DatasetItem"][];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Source */
            source: string;
        };
        /** SourceItem */
        SourceItem: {
            /** Connector Type */
            connector_type: string;
            /** Datasets */
            datasets: number;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Source */
            source: string;
        };
        /**
         * StepRecord
         * @description One step of the version the run ran: its settings, and what it did in this run.
         */
        StepRecord: {
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Ended At */
            ended_at?: string | null;
            /** Error */
            error?: string | null;
            /** Error Line */
            error_line?: number | null;
            /** Output */
            output?: string | null;
            /** Position */
            position: number;
            /** Rows In */
            rows_in?: number | null;
            /** Rows Out */
            rows_out?: number | null;
            /** Script Sha256 */
            script_sha256?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "not_run" | "running" | "succeeded" | "failed";
            /** Type */
            type: string;
            /** Values Changed */
            values_changed?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationRecord
         * @description One constraint checked against the result before it became CLEAN.
         */
        ValidationRecord: {
            /** Columns */
            columns: string[];
            /** Constraint */
            constraint: string;
            /** Critical */
            critical: boolean;
            /** Failing Rows */
            failing_rows: number | null;
            /** Failing Values */
            failing_values: number | null;
            /** Message */
            message: string;
            /** Passed */
            passed: boolean;
            /** Position */
            position: number;
        };
        /** ValueCount */
        ValueCount: {
            /** Count */
            count: number;
            /** Value */
            value: string | number | boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    datasets_api_datasets_get: {
        parameters: {
            query?: {
                q?: string | null;
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_api_datasets__source___dataset__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_config_api_datasets__source___dataset__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_dataset_config_api_datasets__source___dataset__config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_datasets__source___dataset__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_api_datasets__source___dataset__quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rows_api_datasets__source___dataset__rows_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                source: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    pipeline_run_api_pipeline_runs__execution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_pipeline_run_api_pipelines__name__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: {
                source?: string | null;
                dataset?: string | null;
                status?: ("running" | "succeeded" | "failed" | "skipped") | null;
                trigger?: ("manual" | "scheduled") | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_sources_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_api_sources__source__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
