/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{source}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset */
        get: operations["dataset_api_datasets__source___dataset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{source}/{dataset}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality */
        get: operations["quality_api_datasets__source___dataset__quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{source}/{dataset}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rows */
        get: operations["rows_api_datasets__source___dataset__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_sources__source__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckResult */
        CheckResult: {
            /** Check Type */
            check_type: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Columns */
            columns: string[];
            /** Failing Rows */
            failing_rows: number | null;
            /** Message */
            message: string;
            /** Passed */
            passed: boolean;
            /** Position */
            position: number;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /**
             * Severity
             * @enum {string}
             */
            severity: "warn" | "error";
            /** Table Rows */
            table_rows: number | null;
        };
        /** Column */
        Column: {
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** DatasetDetail */
        DatasetDetail: {
            /** Columns */
            columns: components["schemas"]["Column"][];
            /** Dataset */
            dataset: string;
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            last_run: components["schemas"]["RunSummary"] | null;
            /** Load Mode */
            load_mode: string;
            /** Primary Key */
            primary_key: string[];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Schedule */
            schedule: string | null;
            /** Source */
            source: string;
            state: components["schemas"]["SavedState"] | null;
            /** Table Name */
            table_name: string;
            /** Versions */
            versions: components["schemas"]["SchemaVersion"][];
            /** Watermark */
            watermark: string | null;
        };
        /** DatasetItem */
        DatasetItem: {
            /** Dataset */
            dataset: string;
            last_run: components["schemas"]["RunSummary"] | null;
            /** Load Mode */
            load_mode: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Schedule */
            schedule: string | null;
            /** Source */
            source: string;
            /** Table Name */
            table_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
        };
        /** QualityReport */
        QualityReport: {
            /** Results */
            results: components["schemas"]["CheckResult"][];
            /** Run Id */
            run_id: string | null;
        };
        /** RowsPage */
        RowsPage: {
            /** Columns */
            columns: components["schemas"]["Column"][];
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: {
                [key: string]: string | number | boolean | null;
            }[];
        };
        /** RunAccepted */
        RunAccepted: {
            /** Datasets */
            datasets: string[];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Source */
            source: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Dataset */
            dataset: string;
            /** Ended At */
            ended_at: string | null;
            /** Error Class */
            error_class: string | null;
            /** Error Message */
            error_message: string | null;
            /** Error Traceback */
            error_traceback: string | null;
            /** Quality */
            quality: components["schemas"]["CheckResult"][];
            /** Rows Extracted */
            rows_extracted: number | null;
            /** Rows Loaded */
            rows_loaded: number | null;
            /** Rows Quarantined */
            rows_quarantined: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "skipped";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "scheduled";
        };
        /** RunItem */
        RunItem: {
            /** Dataset */
            dataset: string;
            /** Ended At */
            ended_at: string | null;
            /** Error Class */
            error_class: string | null;
            /** Error Message */
            error_message: string | null;
            /** Rows Extracted */
            rows_extracted: number | null;
            /** Rows Loaded */
            rows_loaded: number | null;
            /** Rows Quarantined */
            rows_quarantined: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "skipped";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "scheduled";
        };
        /** RunRequest */
        RunRequest: {
            /** Dataset */
            dataset?: string | null;
            /** Source */
            source: string;
        };
        /** RunSummary */
        RunSummary: {
            /** Ended At */
            ended_at: string | null;
            /** Rows Loaded */
            rows_loaded?: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "skipped";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "scheduled";
        };
        /** RunsPage */
        RunsPage: {
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Runs */
            runs: components["schemas"]["RunItem"][];
        };
        /** SavedState */
        SavedState: {
            /** File Path */
            file_path: string | null;
            /** File Sha256 */
            file_sha256: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            /** Watermark */
            watermark: string | null;
            /** Watermark Column */
            watermark_column: string | null;
            /** Watermark Type */
            watermark_type: string | null;
        };
        /** SchemaVersion */
        SchemaVersion: {
            /** Columns */
            columns: components["schemas"]["Column"][];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Version */
            version: number;
        };
        /** SourceDetail */
        SourceDetail: {
            /** Connection */
            connection: {
                [key: string]: unknown;
            };
            /** Connector Type */
            connector_type: string;
            /** Datasets */
            datasets: components["schemas"]["DatasetItem"][];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Source */
            source: string;
        };
        /** SourceItem */
        SourceItem: {
            /** Connector Type */
            connector_type: string;
            /** Datasets */
            datasets: number;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Source */
            source: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    datasets_api_datasets_get: {
        parameters: {
            query?: {
                q?: string | null;
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_api_datasets__source___dataset__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_api_datasets__source___dataset__quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rows_api_datasets__source___dataset__rows_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                source: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: {
                source?: string | null;
                dataset?: string | null;
                status?: ("running" | "succeeded" | "failed" | "skipped") | null;
                trigger?: ("manual" | "scheduled") | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_sources_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_api_sources__source__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
